remote_theme: pages-themes/leap-day@v0.2.0
plugins:
- jekyll-remote-theme

title: Development and Evaluation of a Linear Regression Model to Predict ADC KDA Ratios Using Postgame Data

description: This page follows the creation and assessment of a predictive model using linear regression to predict Kill-Death-Assist (KDA) ratios specifically tailored for Attack Damage Carry (ADC) champions based on postgame data.
